# Testing Configuration
debug: false
log_level: WARNING

database:
  url: sqlite:///temp/test.db
  echo: false

redis:
  url: redis://localhost:6379/1

inversion:
  default_method: fallback
  max_iterations: 10
  cache_results: false

ml:
  model_cache_dir: temp/test_models
  feature_cache_dir: temp/test_features
  default_cv_folds: 3

logging:
  level: WARNING
  format: "%(levelname)s - %(message)s"
